### ISSUE TITLE
About code to generate synthetic pairs for AFHQ dataset

### ISSUE THREAD

**Issue by huaishengzhu** [sangyun884/rfpp#2]
Hi, 

I hope this message finds you well. Thanks for your sharing your code! I noticed that you didn't provide the command to generated synthetic pairs for the AFHQ dataset. Could you please share this?

Thank you for your assistance!

Best,

**Comment by sangyun884** [comment]
You can simply modify the options following Appendix E. Configs are given in [configs_unet](https://github.com/sangyun884/rfpp/tree/main/configs_unet), and EDM checkpoints are provided in README.

**Comment by huaishengzhu** [comment]
Thanks for your reply! I will try to use this.
